### PR TITLE
feat: additional security parameter for the Ledger

### PR DESCRIPTION
**Pull request by chrisdukakis**
This PR adds support for mining bundles that can be signed on Ledger devices. Related to https://github.com/iotaledger/iota_common/pull/4

- Points `iota_common` to iotaledger/iota_common@7b98956

- Implements `fullySecure` flag

### CODE REVIEW

**Comment by chrisdukakis** [comment]
It seems that needed changes in `iota_common` were overwritten by this [merge](https://github.com/iotaledger/iota_common/commit/a79558b55a0f686f136ffaf98eec2734aad8f91a). Perhaps we need to add them again and point iota_common to latest.

**Comment by rajivshah3** [comment]
I re-added the `fully_secure` parameter in https://github.com/iotaledger/iota_common/pull/11

**Comment by rajivshah3** [comment]
iotaledger/iota_common@3b19e217f1d539f712b7e3a47050202aab9096df includes the `fully_secure` parameter

**Comment by chrisdukakis** [comment]
Thanks Rajiv! I'll update the PR.

**Comment by laumair** [comment]
Nice work! @chrisdukakis

**Pull request merged**
